### ISSUE TITLE
[Bug]: miui14 闪退

### ISSUE THREAD

**Issue by shugo-chara** [lihenggui/blocker#160]
### Is there an existing issue for this?

- [X] I have searched the existing issues

### Is there a StackOverflow question about this issue?

- [X] I have searched StackOverflow

### What happened?

MIUI14 mix fold2 Android13
magisk delta
安装2.0版反复闪退

### Relevant logcat output

```shell
java.lang.SecurityException: Unknown calling package name 'com.merxury.blocker'.
	at android.os.Parcel.createExceptionOrNull(Parcel.java:3011)
	at android.os.Parcel.createException(Parcel.java:2995)
	at android.os.Parcel.readException(Parcel.java:2978)
	at android.os.Parcel.readException(Parcel.java:2920)
	at u6.m.n(Unknown Source:31)
	at u6.b$d.a(SourceFile:109)
	at u6.x.f(Unknown Source:8)
	at u6.k.a(SourceFile:9)
	at u6.s.handleMessage(SourceFile:363)
	at android.os.Handler.dispatchMessage(Handler.java:106)
	at android.os.Looper.loopOnce(Looper.java:210)
	at android.os.Looper.loop(Looper.java:299)
	at android.app.ActivityThread.main(ActivityThread.java:8252)
	at java.lang.reflect.Method.invoke(Native Method)
	at com.android.internal.os.RuntimeInit$MethodAndArgsCaller.run(RuntimeInit.java:559)
	at com.android.internal.os.ZygoteInit.main(ZygoteInit.java:954)
```

**Comment by lihenggui** [comment]
```
Fatal Exception: java.lang.SecurityException: Unknown calling package name 'com.merxury.blocker'.
       at android.os.Parcel.createExceptionOrNull(Parcel.java:2426)
       at android.os.Parcel.createException(Parcel.java:2410)
       at android.os.Parcel.readException(Parcel.java:2393)
       at android.os.Parcel.readException(Parcel.java:2335)
       at com.google.android.gms.common.internal.zzac.getService(zzac.java:31)
       at com.google.android.gms.common.internal.BaseGmsClient.getRemoteService(BaseGmsClient.java:109)
       at com.google.android.gms.common.internal.BaseGmsClient$LegacyClientCallbackAdapter.onReportServiceBinding(BaseGmsClient.java:109)
       at com.google.android.gms.common.internal.zzg.zzd(zzg.java:8)
       at com.google.android.gms.common.internal.zza.a(zza.java:9)
       at com.google.android.gms.common.internal.zzc.zze(zzc.java:363)
       at com.google.android.gms.common.internal.zzb.handleMessage(zzb.java:363)
       at android.os.Handler.dispatchMessage(Handler.java:106)
       at android.os.Looper.loopOnce(Looper.java:201)
       at android.os.Looper.loop(Looper.java:288)
       at android.app.ActivityThread.main(ActivityThread.java:7870)
       at java.lang.reflect.Method.invoke(Method.java)
       at com.android.internal.os.RuntimeInit$MethodAndArgsCaller.run(RuntimeInit.java:548)
       at com.android.internal.os.ZygoteInit.main(ZygoteInit.java:1003)
```
Caused by GMS plugin

**Comment by lihenggui** [comment]
这个是升级最新的GMS+Firebase依赖的版本，可以帮我测试一下可否正常使用吗？
[app-compose-market-release.apk.zip](https://github.com/lihenggui/blocker/files/11194050/app-compose-market-release.apk.zip)

这个是完整移除gms+Firebase的版本，这个肯定是可以使用的
[app-compose-foss-release.apk.zip](https://github.com/lihenggui/blocker/files/11194051/app-compose-foss-release.apk.zip)

请注意这两个压缩包的签名和市场上的不一致，安装的时候请卸载原先的版本进行测试。感谢。

**Comment by shugo-chara** [comment]
>GMS+Firebase依赖的版本依旧闪退，报错原因与之前相同。我的本机gms是最新 。
无GMS+Firebase的确实正常打开了。。

**Comment by lihenggui** [comment]
无法拉起请求应该是没正常授权导致的，不应该会出现这个问题。
我给你出一个foss的最新包，稍等下

**Comment by lihenggui** [comment]
Caused by: https://github.com/firebase/firebase-android-sdk/issues/5024

**Comment by lihenggui** [comment]
Comment in https://github.com/firebase/firebase-android-sdk/issues/5024
> This was fixed (see mitigation above). Please update to latest version to get these changes and feel free to open a new issue if this problem continues.
