### ISSUE TITLE
[Bug]: IllegalStateException: LayoutNode should be attached to an owner

### ISSUE THREAD

**Issue by LinMingkui** [lihenggui/blocker#314]
### Is there an existing issue for this?

- [X] I have searched the existing issues

### Is there a StackOverflow question about this issue?

- [X] I have searched StackOverflow

### What happened?

点击这个闪退
![image](https://github.com/lihenggui/blocker/assets/47204593/a65a4d16-ea1f-481c-86b7-e1e0ff298557)

### Relevant logcat output

```shell
FATAL EXCEPTION: main
Process: com.merxury.blocker, PID: 19615
java.lang.IllegalStateException: LayoutNode should be attached to an owner
	at u0.g.A(SourceFile:14)
	at u0.M.q0(SourceFile:20)
	at u0.M.h0(SourceFile:74)
	at s0.c0.k(SourceFile:28)
	at s0.c0.l(SourceFile:13)
	at v.z.b(SourceFile:137)
	at r.G.invoke(SourceFile:51)
	at s0.S.d(SourceFile:37)
	at v.y.d(SourceFile:1)
	at s0.E.d(SourceFile:25)
	at q.W.invoke(SourceFile:32)
	at q.W.invoke(SourceFile:155)
	at S2.j.t(SourceFile:60)
	at X.y.a(SourceFile:52)
	at X.z.c(SourceFile:61)
	at u0.n0.a(SourceFile:3)
	at u0.M.I(SourceFile:105)
	at u0.M.p0(SourceFile:126)
	at u0.v.h0(SourceFile:18)
	at s0.c0.b(SourceFile:33)
	at q.l.invoke(SourceFile:6)
	at q.l.invoke(SourceFile:3)
	at s0.S.d(SourceFile:37)
	at u0.A.h0(SourceFile:42)
	at s0.c0.i(SourceFile:32)
	at s0.c0.j(SourceFile:13)
	at q.l.invoke(SourceFile:12)
	at q.l.invoke(SourceFile:4)
	at s0.S.d(SourceFile:37)
	at u0.A.h0(SourceFile:42)
	at s0.c0.i(SourceFile:32)
	at s0.c0.j(SourceFile:13)
	at q.s.invoke(SourceFile:170)
	at q.s.invoke(SourceFile:70)
	at s0.S.d(SourceFile:37)
	at u0.A.h0(SourceFile:42)
	at s0.c0.d(SourceFile:29)
	at u0.L.invoke(SourceFile:15)
	at S2.j.t(SourceFile:60)
	at X.y.a(SourceFile:52)
	at X.z.c(SourceFile:61)
	at u0.n0.a(SourceFile:3)
	at u0.M.q0(SourceFile:95)
	at u0.G.P(SourceFile:32)
	at u0.S.k(SourceFile:209)
	at u0.S.g(SourceFile:91)
	at androidx.compose.ui.platform.AndroidComposeView.v(SourceFile:34)
	at u0.j0.a(SourceFile:4)
	at androidx.compose.ui.platform.AndroidComposeView.dispatchDraw(SourceFile:14)
	at android.view.View.draw(View.java:23347)
	at android.view.View.updateDisplayListIfDirty(View.java:22201)
	at android.view.ViewGroup.recreateChildDisplayList(ViewGroup.java:4527)
	at android.view.ViewGroup.dispatchGetDisplayList(ViewGroup.java:4500)
	at android.view.View.updateDisplayListIfDirty(View.java:22151)
	at android.view.ViewGroup.recreateChildDisplayList(ViewGroup.java:4527)
	at android.view.ViewGroup.dispatchGetDisplayList(ViewGroup.java:4500)
	at android.view.View.updateDisplayListIfDirty(View.java:22151)
	at android.view.ViewGroup.recreateChildDisplayList(ViewGroup.java:4527)
	at android.view.ViewGroup.dispatchGetDisplayList(ViewGroup.java:4500)
	at android.view.View.updateDisplayListIfDirty(View.java:22151)
	at android.view.ViewGroup.recreateChildDisplayList(ViewGroup.java:4527)
	at android.view.ViewGroup.dispatchGetDisplayList(ViewGroup.java:4500)
	at android.view.View.updateDisplayListIfDirty(View.java:22151)
	at android.view.ThreadedRenderer.updateViewTreeDisplayList(ThreadedRenderer.java:682)
	at android.view.ThreadedRenderer.updateRootDisplayList(ThreadedRenderer.java:690)
	at android.view.ThreadedRenderer.draw(ThreadedRenderer.java:795)
	at android.view.ViewRootImpl.draw(ViewRootImpl.java:4875)
	at android.view.ViewRootImpl.performDraw(ViewRootImpl.java:4576)
	at android.view.ViewRootImpl.performTraversals(ViewRootImpl.java:3780)
	at android.view.ViewRootImpl.doTraversal(ViewRootImpl.java:2518)
	at android.view.ViewRootImpl$TraversalRunnable.run(ViewRootImpl.java:9389)
	at android.view.Choreographer$CallbackRecord.run(Choreographer.java:1451)
	at android.view.Choreographer$CallbackRecord.run(Choreographer.java:1459)
	at android.view.Choreographer.doCallbacks(Choreographer.java:1089)
	at android.view.Choreographer.doFrame(Choreographer.java:1003)
	at android.view.Choreographer$FrameDisplayEventReceiver.run(Choreographer.java:1431)
	at android.os.Handler.handleCallback(Handler.java:942)
	at android.os.Handler.dispatchMessage(Handler.java:99)
	at android.os.Looper.loopOnce(Looper.java:210)
	at android.os.Looper.loop(Looper.java:299)
	at android.app.ActivityThread.main(ActivityThread.java:8261)
	at java.lang.reflect.Method.invoke(Native Method)
	at com.android.internal.os.RuntimeInit$MethodAndArgsCaller.run(RuntimeInit.java:559)
	at com.android.internal.os.ZygoteInit.main(ZygoteInit.java:954)
```
```

**Comment by juliewww** [comment]
Fixed in https://github.com/lihenggui/blocker/pull/317.
