### ISSUE TITLE
[Bug]: F-Droid builds cannot fetch online rules

### ISSUE THREAD

**Issue by Guanran928** [lihenggui/blocker#542]
### Is there an existing issue for this?

- [X] I have searched the existing issues

### Is there a StackOverflow question about this issue?

- [X] I have searched StackOverflow

### What happened?

After installing F-Droid's build of Blocker, I noticed that online rules won't load at all. (with both GitHub and GitLab source)

I cannot reproduce this with binary in GitHub Release.
(`Blocker-2.0.3058-foss-release.apk`)

version: 2.0.3058-fdroid
os: LineageOS 20 unofficial

cc: @linsui

#469 might be relevant

![photo_2023-11-27_19-50-09](https://github.com/lihenggui/blocker/assets/68757440/415da158-fde3-49b0-b37a-8cdfcd07d1c3)

**Comment by linsui** [comment]
```
11-27 19:47:39.919  3882  3918 E WM-WorkerWrapper: Work [ id=45bc7fb2-8369-4898-bbba-0bba04766954, tags={ com.merxury.blocker.core.rule.work.CopyRulesToStorageWorker, CopyRuleToInternalStorage } ] failed because it threw an exception/error
11-27 19:47:39.919  3882  3918 E WM-WorkerWrapper: java.util.concurrent.ExecutionException: java.lang.IllegalArgumentException: No files found in blocker-general-rules
11-27 19:47:39.919  3882  3918 E WM-WorkerWrapper: 	at q5.h.e(SourceFile:21)
11-27 19:47:39.919  3882  3918 E WM-WorkerWrapper: 	at q5.h.get(SourceFile:119)
11-27 19:47:39.919  3882  3918 E WM-WorkerWrapper: 	at j.h.run(SourceFile:339)
11-27 19:47:39.919  3882  3918 E WM-WorkerWrapper: 	at j.h.b(SourceFile:5)
11-27 19:47:39.919  3882  3918 E WM-WorkerWrapper: 	at j.h.run(SourceFile:192)
11-27 19:47:39.919  3882  3918 E WM-WorkerWrapper: 	at java.util.concurrent.ThreadPoolExecutor.runWorker(ThreadPoolExecutor.java:1137)
11-27 19:47:39.919  3882  3918 E WM-WorkerWrapper: 	at java.util.concurrent.ThreadPoolExecutor$Worker.run(ThreadPoolExecutor.java:637)
11-27 19:47:39.919  3882  3918 E WM-WorkerWrapper: 	at java.lang.Thread.run(Thread.java:1012)
11-27 19:47:39.919  3882  3918 E WM-WorkerWrapper: Caused by: java.lang.IllegalArgumentException: No files found in blocker-general-rules
11-27 19:47:39.919  3882  3918 E WM-WorkerWrapper: 	at com.merxury.blocker.core.rule.work.CopyRulesToStorageWorker$doWork$2.invokeSuspend(SourceFile:301)
11-27 19:47:39.919  3882  3918 E WM-WorkerWrapper: 	at g8.a.resumeWith(SourceFile:9)
11-27 19:47:39.919  3882  3918 E WM-WorkerWrapper: 	at w8.j0.run(SourceFile:116)
11-27 19:47:39.919  3882  3918 E WM-WorkerWrapper: 	at j.h.run(SourceFile:687)
11-27 19:47:39.919  3882  3918 E WM-WorkerWrapper: 	at c9.i.run(SourceFile:3)
11-27 19:47:39.919  3882  3918 E WM-WorkerWrapper: 	at c9.a.run(SourceFile:94)
11-27 19:47:39.921  3882  3918 I WM-WorkerWrapper: Worker result FAILURE for Work [ id=45bc7fb2-8369-4898-bbba-0bba04766954, tags={ com.merxury.blocker.core.rule.work.CopyRulesToStorageWorker, CopyRuleToInternalStorage } ]
11-27 19:47:39.937  3882  3995 D InitializeRuleStorageUseCase$invoke: WorkInfo: [CopyRuleToInternalStorage, com.merxury.blocker.core.rule.work.CopyRulesToStorageWorker], state = FAILED
```

Not sure if this is related.

**Comment by lihenggui** [comment]
Emm, you notified me that I haven't updated the F-droid version. I will push a new version once I finish it

**Comment by linsui** [comment]
It's fixed, thanks!
