### ISSUE TITLE
新的Android版本上用ifw也会抛出异常导致crash了，，，SecurityException之类

### ISSUE THREAD

**Issue by cervy** [lihenggui/blocker#56]

**Comment by cervy** [comment]
java.lang.RuntimeException: Unable to start receiver miui.autoinstall.config.receiver.SystemBootBroadCastReceiver: java.lang.SecurityException Not allowed to start service Intent {act=android.intent.action.BOOT_COMPLETED cmp=com.miui.core/ miui.autoinstall.config.service.AutolnstallService } without permission blocked by firewall

**Comment by lihenggui** [comment]
@cervy 请提供一下bugreport文件，我反馈给 Google

**Comment by lihenggui** [comment]
这个看起来像是MIUI的问题

**Comment by cervy** [comment]
非系统应用也有这个异常

**Comment by cervy** [comment]
非系统应用也有这个异常，如
java.lang.RuntimeException: Unable to create application com.baidu.netdisk.ShellApplication: java.lang.SecurityException: Not allowed to bind to service Intent { cmp=com.baidu.netdisk/.service.AdvertiseNetdiskService }
	at android.app.ActivityThread.handleBindApplication(ActivityThread.java:7079)
	at android.app.ActivityThread.access$1600(ActivityThread.java:274)
	at android.app.ActivityThread$H.handleMessage(ActivityThread.java:2129)
	at android.os.Handler.dispatchMessage(Handler.java:106)
	at android.os.Looper.loopOnce(Looper.java:210)
	at android.os.Looper.loop(Looper.java:299)
	at android.app.ActivityThread.main(ActivityThread.java:8265)
	at java.lang.reflect.Method.invoke(Native Method)
	at com.android.internal.os.RuntimeInit$MethodAndArgsCaller.run(RuntimeInit.java:556)
	at com.android.internal.os.ZygoteInit.main(ZygoteInit.java:1045)
Caused by: java.lang.SecurityException: Not allowed to bind to service Intent { cmp=com.baidu.netdisk/.service.AdvertiseNetdiskService }
	at android.app.ContextImpl.bindServiceCommon(ContextImpl.java:1994)
	at android.app.ContextImpl.bindService(ContextImpl.java:1906)
	at android.content.ContextWrapper.bindService(ContextWrapper.java:820)
	at com.baidu.netdisk.NetDiskApplication.bindService(SourceFile:1168)
	at com.baidu.netdisk.NetDiskApplication.onSyncInit(SourceFile:486)
	at com.baidu.netdisk.ShellApplication.onSyncInit(SourceFile:133)
	at com.baidu.netdisk.NetDiskApplication.initApp(SourceFile:383)
	at com.baidu.netdisk.kernel.BaseApplication.selfCreateOperation(SourceFile:70)
	at com.baidu.netdisk.NetDiskApplication.basecreateOperation(SourceFile:289)
	at com.baidu.netdisk.NetDiskApplication.onCreate(SourceFile:276)
	at android.app.Instrumentation.callApplicationOnCreate(Instrumentation.java:1211)
	at android.app.ActivityThread.handleBindApplication(ActivityThread.java:7073)
	... 9 more

**Comment by cervy** [comment]
> 

是用的miui 13

**Comment by lihenggui** [comment]
@cervy 可以提供完整的bugreport分析吗，这样我可以看到上下文情况

https://dev.mi.com/docs/appsmarket/technical_docs/attain_bug_report/

**Comment by lihenggui** [comment]
Hi @cervy  如果有bugreport的话请贴在这个issue中，我先关掉这个
