### ISSUE TITLE
[Bug]: Crash sometimes when tapping rules section

### ISSUE THREAD

**Issue by zputnyq** [lihenggui/blocker#739]
### Is there an existing issue for this?

- [X] I have searched the existing issues

### Is there a StackOverflow question about this issue?

- [X] I have searched StackOverflow

### What happened?

It's fresh install & I haven't set anything yet. When I tap rules section it's crash, but it no longer happen when I don't wipe blocker from recent, in rules section there is only rounding precentage without progress (0℅).

Device
Xperia M4 stock android 6.0.1
Blocker-2.0.3926-foss-release

### Relevant logcat output

```shell
java.lang.IllegalArgumentException: Bad position (limit 110): -16164
	at java.nio.Buffer.positionImpl(Buffer.java:351)
	at java.nio.Buffer.position(Buffer.java:345)
	at java.nio.charset.CharsetDecoderICU.setPosition(CharsetDecoderICU.java:205)
	at java.nio.charset.CharsetDecoderICU.decodeLoop(CharsetDecoderICU.java:154)
	at java.nio.charset.CharsetDecoder.decode(CharsetDecoder.java:306)
	at eb.j.a(SourceFile:131)
	at eb.f0.E(SourceFile:33)
	at eb.f0.o(SourceFile:13)
	at eb.f0.c(SourceFile:1)
	at eb.g0.j0(SourceFile:36)
	at cb.a.f(SourceFile:55)
	at cb.a.deserialize(SourceFile:7)
	at eb.g0.Z(SourceFile:104)
	at x5.f.u(SourceFile:11)
	at eb.g0.u(SourceFile:50)
	at com.merxury.blocker.core.network.model.NetworkGeneralRule$$serializer.deserialize(SourceFile:1)
	at com.merxury.blocker.core.network.model.NetworkGeneralRule$$serializer.deserialize(SourceFile:2)
	at eb.g0.Z(SourceFile:104)
	at x5.f.u(SourceFile:11)
	at eb.g0.u(SourceFile:50)
	at cb.u.h(SourceFile:8)
	at cb.a.f(SourceFile:64)
	at cb.a.deserialize(SourceFile:7)
	at eb.g0.Z(SourceFile:104)
	at ra.c1.y(SourceFile:26)
	at ra.c1.z(SourceFile:11)
	at com.merxury.blocker.core.data.respository.generalrule.LocalGeneralRuleDataSource$getGeneralRules$1.invokeSuspend(SourceFile:122)
	at com.merxury.blocker.core.data.respository.generalrule.LocalGeneralRuleDataSource$getGeneralRules$1.invoke(SourceFile:2)
	at com.merxury.blocker.core.data.respository.generalrule.LocalGeneralRuleDataSource$getGeneralRules$1.invoke(SourceFile:1)
	at t5.g.collect(SourceFile:79)
	at sa.j.g(SourceFile:3)
	at sa.i.collect(SourceFile:46)
	at com.merxury.blocker.core.data.respository.generalrule.OfflineFirstGeneralRuleRepository$updateGeneralRule$$inlined$map$1.collect(SourceFile:8)
	at ra.u.collect(SourceFile:34)
	at e4.x.collect(SourceFile:32)
	at a0.e.p(SourceFile:70)
	at ra.n.collect(SourceFile:70)
	at ra.l.collect(SourceFile:109)
	at sa.j.g(SourceFile:3)
	at sa.i.d(SourceFile:6)
	at sa.f.invokeSuspend(SourceFile:33)
	at y9.a.resumeWith(SourceFile:9)
	at oa.m0.run(SourceFile:115)
	at k.j.run(SourceFile:14)
	at ua.j.run(SourceFile:3)
	at ua.a.run(SourceFile:96)
```

**Comment by lihenggui** [comment]
@zputnyq Is this issue always happening on your device?

**Comment by zputnyq** [comment]
> @zputnyq Is this issue always happening on your device?

Yes actually

**Comment by lihenggui** [comment]
Caused by https://github.com/Kotlin/kotlinx.serialization/issues/2457

**Comment by lihenggui** [comment]
@zputnyq Please check 
https://github.com/lihenggui/blocker/releases/tag/v2.0.3961

**Comment by zputnyq** [comment]
> @zputnyq Please check https://github.com/lihenggui/blocker/releases/tag/v2.0.3961

Thank you, I can confirm working fine on v2.0.3961
