### ISSUE TITLE
sdk/trackers无法加载，一直显示0%

### ISSUE THREAD

**Issue by GordonYoungCao** [lihenggui/blocker#950]
![Screenshot_2024-08-15-00-26-20-889_com merxury blocker](https://github.com/user-attachments/assets/80827159-c72c-4ae0-a3a6-154f1ecc72d3)
[2024-08-15.log](https://github.com/user-attachments/files/16616161/2024-08-15.log)

**Comment by lihenggui** [comment]
```
2024-08-14T16:26:06.421Z E/LocalGeneralRuleDataSource$getGeneralRules: No general rule file found
2024-08-14T16:26:06.439Z E/LocalGeneralRuleDataSource$getRuleFile: General rule file not found, language: en
2024-08-14T16:26:06.440Z D/LocalGeneralRuleDataSource$getRuleFileFromAssets: Get rule file from assets, language: en
2024-08-14T16:26:06.441Z E/LocalGeneralRuleDataSource$getRuleFileFromAssets: Failed to get rule file from assets
java.io.FileNotFoundException: blocker-general-rules/rules/en/general.json
	at android.content.res.AssetManager.nativeOpenAsset(Native Method)
	at android.content.res.AssetManager.open(AssetManager.java:919)
	at android.content.res.AssetManager.open(AssetManager.java:896)
	at com.merxury.blocker.core.data.respository.generalrule.LocalGeneralRuleDataSource$getRuleFileFromAssets$2.invokeSuspend(SourceFile:65)
	at com.merxury.blocker.core.data.respository.generalrule.LocalGeneralRuleDataSource$getRuleFileFromAssets$2.invoke(SourceFile:1)
	at com.merxury.blocker.core.data.respository.generalrule.LocalGeneralRuleDataSource$getRuleFileFromAssets$2.invoke(SourceFile:2)
	at a1.p.K(SourceFile:5)
	at a5.F.G(SourceFile:74)
	at com.merxury.blocker.core.data.respository.generalrule.LocalGeneralRuleDataSource.getRuleFileFromAssets(SourceFile:9)
	at com.merxury.blocker.core.data.respository.generalrule.LocalGeneralRuleDataSource.access$getRuleFileFromAssets(SourceFile:1)
	at com.merxury.blocker.core.data.respository.generalrule.LocalGeneralRuleDataSource$getGeneralRules$1.invokeSuspend(SourceFile:172)
	at J4.a.resumeWith(SourceFile:9)
	at g5.r.d(SourceFile:7)
	at a5.a.resumeWith(SourceFile:23)
	at J4.a.resumeWith(SourceFile:32)
	at a5.M.run(SourceFile:115)
	at C2.b.run(SourceFile:412)
	at i5.k.run(SourceFile:3)
	at i5.a.run(SourceFile:96)
```

**Comment by GordonYoungCao** [comment]
> 清除数据会解决这个问题吗

我卸载重装后就没问题了，但是第一次从ifw模式切换到sui模式，会提示“无法获取权限，应用可能无法正常工作”，之后再随意切换模式，就没有这个提示
[2024-08-15.log](https://github.com/user-attachments/files/16620086/2024-08-15.log)

**Comment by lihenggui** [comment]
```
2024-09-07T11:14:33.729Z E/LocalGeneralRuleDataSource$getRuleFileFromAssets: Failed to get rule file from assets
java.io.FileNotFoundException: blocker-general-rules/rules/zh-CN/general.json
	at android.content.res.AssetManager.openAsset(Native Method)
	at android.content.res.AssetManager.open(AssetManager.java:474)
	at android.content.res.AssetManager.open(AssetManager.java:448)
	at com.merxury.blocker.core.data.respository.generalrule.LocalGeneralRuleDataSource$getRuleFileFromAssets$2.invokeSuspend(SourceFile:65)
	at com.merxury.blocker.core.data.respository.generalrule.LocalGeneralRuleDataSource$getRuleFileFromAssets$2.invoke(SourceFile:1)
	at com.merxury.blocker.core.data.respository.generalrule.LocalGeneralRuleDataSource$getRuleFileFromAssets$2.invoke(SourceFile:2)
	at Z2.b.S(SourceFile:5)
	at Z4.F.G(SourceFile:74)
	at com.merxury.blocker.core.data.respository.generalrule.LocalGeneralRuleDataSource.getRuleFileFromAssets(SourceFile:9)
	at com.merxury.blocker.core.data.respository.generalrule.LocalGeneralRuleDataSource.access$getRuleFileFromAssets(SourceFile:1)
	at com.merxury.blocker.core.data.respository.generalrule.LocalGeneralRuleDataSource$getGeneralRules$1.invokeSuspend(SourceFile:172)
	at I4.a.resumeWith(SourceFile:9)
	at Z4.M.run(SourceFile:107)
	at B2.b.run(SourceFile:412)
	at h5.k.run(SourceFile:3)
	at h5.a.run(SourceFile:96)
```

**Comment by lihenggui** [comment]
> 使用 F-Droid 版本（测试了 2.0.4373 和 2.0.4497）同样遇到此问题，清除数据无效，切换到 GitHub FOSS 版本后正常 [2024-09-07.log](https://github.com/user-attachments/files/16917885/2024-09-07.log)

检查了一下，FDroid的版本在打包APK的时候没有clone内置规则，需要修改编译脚本

**Comment by linsui** [comment]
Will be fixed after two updates.

**Comment by lihenggui** [comment]
> Will be fixed after two updates.

Thanks!

**Comment by lihenggui** [comment]
The APK provided by fdroid includes assets now. Thanks @linsui 
https://f-droid.org/zh_Hans/packages/com.merxury.blocker/
